name: zest
description: Task management application.

publish_to: "none"

version: 1.6.0+54

environment:
  sdk: ">=3.10.7 <4.0.0"
  flutter: "^3.38.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.7.3
  gap: ^3.0.1
  path: ^1.9.1
  intl: ^0.20.2
  archive: ^4.0.7
  timezone: ^0.10.1
  flag_secure: ^2.0.2
  # workmanager: ^0.9.0+3
  # home_widget: ^0.9.0
  quick_actions: ^1.1.0
  restart_app: ^1.3.2
  reorderables: ^0.6.0
  google_fonts: ^7.0.2
  url_launcher: ^6.3.2
  iconsax_plus: ^1.0.0
  display_mode: ^0.0.2
  dynamic_color: ^1.8.1
  path_provider: ^2.1.5
  file_selector: ^1.1.0
  table_calendar: ^3.2.0
  flutter_timezone: ^5.0.1
  device_info_plus: ^12.3.0
  package_info_plus: ^9.0.0
  flex_color_picker: ^3.8.0
  omni_datetime_picker: ^2.3.1
  line_awesome_flutter: ^3.0.1
  sleek_circular_slider: ^2.1.0
  flutter_local_notifications: ^19.5.0
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.1
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  isar_community_generator: ^3.3.0

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#181818"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#181818"
  android_12:
    color: "#181818"
  image: "assets/icons/icon.png"

flutter:
  generate: false
  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Light.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
